### ISSUE TITLE
proto file missing

### ISSUE THREAD

**Issue by mhaberler** [Ivanf1/esp32-protobuf-sensors#1]
very interesting idea - will reuse!

would you mind including the .proto file which defines the temperature and humidity fields?

Michael

**Comment by Ivanf1** [comment]
Thank you Micheal! I added it in the last commit.

**Comment by mhaberler** [comment]
thanks, really appreciated!

btw re integration of nanopb into platformio..

I did a rough haque to run the generator inside vscode/pio
it is a gross wart, but maybe a starting point for something more generally usable (lacking Scons+Pio clue unfortunately)

**Comment by Ivanf1** [comment]
Nanopb integration in platformio would be great! Unfortunately, at the moment, I don't have much time to work on this, but I will take a look.
